apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "default"
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: "default"
        slack_configs:
          - api_url: ''
            channel: '#to-do-app'
            send_resolved: true

        email_configs:
          - to: ''
            from: ''
            smarthost: 'smtp.example.com:587'
            auth_username: ''
            auth_identity: ''
            auth_password: ''
            send_resolved: true
