apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-app-rc
spec:
  replicas: 3
  selector:
    app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: flask-app
        image: username/todo-app:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 5000
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
        - name: mongo-storage
          emptyDir: {}
