apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  labels:
    role: alert-rules
data:
  alert.rules: |
    groups:
    - name: kubernetes-apps
      rules:
      - alert: PodCrashLoopBackOff
        # This expression triggers an alert when any container in a pod has restarted more than 5 times
        expr: kube_pod_container_status_restarts_total > 5
        for: 5m  # Alert fires if the condition is met for 5 minutes
        labels:
          severity: critical
        annotations:
          summary: "Pod crash loop detected"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 5 times in the last 5 minutes."
